/**
 * Common-Cents - Frontend App
 * Auto-generated by Module Library Assembler with AI
 */
import React, { useState, useEffect } from 'react';
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom';
import { Menu, X } from 'lucide-react';
import './theme.css';
// Page imports
import HomePage from './pages/HomePage';
import AboutPage from './pages/AboutPage';
import ContactPage from './pages/ContactPage';
import FaqPage from './pages/FaqPage';
import DashboardPage from './pages/DashboardPage';
import EarnPage from './pages/EarnPage';
import RewardsPage from './pages/RewardsPage';
import WalletPage from './pages/WalletPage';
import ProfilePage from './pages/ProfilePage';
import LeaderboardPage from './pages/LeaderboardPage';

// Auth components
import { AuthProvider } from './modules/auth-pages/components/AuthProvider';
import { ProtectedRoute } from './modules/auth-pages/components/ProtectedRoute';
import { LoginPage } from './modules/auth-pages/components/LoginPage';
import { RegisterPage } from './modules/auth-pages/components/RegisterPage';
import { useAuth } from './modules/auth-pages/components/AuthProvider';

// Auth navigation buttons
function AuthButtons() {
  const { user, logout } = useAuth();
  
  if (user) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
        <span style={{ color: '#888888', fontSize: '14px' }}>
          {user.fullName || user.email}
        </span>
        <button onClick={logout} style={styles.logoutButton}>
          Logout
        </button>
      </div>
    );
  }
  
  return (
    <div style={{ display: 'flex', gap: '12px' }}>
      <Link to="/login" style={styles.loginButton}>Login</Link>
      <Link to="/register" style={styles.registerButton}>Sign Up</Link>
    </div>
  );
}

// Mobile menu wrapper component
function NavWrapper({ children }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(typeof window !== 'undefined' && window.innerWidth < 768);
  const location = useLocation();

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  useEffect(() => {
    setMenuOpen(false);
  }, [location]);

  return (
    <>
      <nav style={styles.nav}>
        <Link to="/" style={styles.navBrand}>
          <span style={styles.brandText}>Common Cents</span>
        </Link>
        
        {isMobile ? (
          <button 
            onClick={() => setMenuOpen(!menuOpen)} 
            style={styles.hamburger}
            aria-label="Toggle menu"
          >
            {menuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        ) : (
          <>
            <div style={styles.navLinks}>
            <Link to="/" style={styles.navLink}>Home</Link>
            <Link to="/about" style={styles.navLink}>About</Link>
            <Link to="/contact" style={styles.navLink}>Contact</Link>
            <Link to="/faq" style={styles.navLink}>Faq</Link>
            <Link to="/dashboard" style={styles.navLink}>Dashboard</Link>
            <Link to="/earn" style={styles.navLink}>Earn</Link>
            <Link to="/rewards" style={styles.navLink}>Rewards</Link>
            <Link to="/wallet" style={styles.navLink}>Wallet</Link>
            <Link to="/profile" style={styles.navLink}>Profile</Link>
            <Link to="/leaderboard" style={styles.navLink}>Leaderboard</Link>
            </div>
            <div style={styles.navAuth}>

            <AuthButtons />
            </div>
          </>
        )}
      </nav>
      
      {isMobile && menuOpen && (
        <div style={styles.mobileMenuOverlay} onClick={() => setMenuOpen(false)}>
          <div style={styles.mobileMenu} onClick={(e) => e.stopPropagation()}>
            <Link to="/" style={styles.mobileNavLink}>Home</Link>
            <Link to="/about" style={styles.mobileNavLink}>About</Link>
            <Link to="/contact" style={styles.mobileNavLink}>Contact</Link>
            <Link to="/faq" style={styles.mobileNavLink}>Faq</Link>
            <Link to="/dashboard" style={styles.mobileNavLink}>Dashboard</Link>
            <Link to="/earn" style={styles.mobileNavLink}>Earn</Link>
            <Link to="/rewards" style={styles.mobileNavLink}>Rewards</Link>
            <Link to="/wallet" style={styles.mobileNavLink}>Wallet</Link>
            <Link to="/profile" style={styles.mobileNavLink}>Profile</Link>
            <Link to="/leaderboard" style={styles.mobileNavLink}>Leaderboard</Link>
            <div style={styles.mobileAuthButtons}>

            <AuthButtons />
            </div>
          </div>
        </div>
      )}
      {children}
    </>
  );
}

function App() {
  return (
    <AuthProvider>
    <BrowserRouter>
      <div style={styles.app}>
        <NavWrapper>
          {/* Main Content */}
          <main style={styles.main}>
            <Routes>
              <Route path="/" element={<HomePage />} />
              <Route path="/about" element={<AboutPage />} />
              <Route path="/contact" element={<ContactPage />} />
              <Route path="/faq" element={<FaqPage />} />
              <Route path="/dashboard" element={<ProtectedRoute><DashboardPage /></ProtectedRoute>} />
              <Route path="/earn" element={<ProtectedRoute><EarnPage /></ProtectedRoute>} />
              <Route path="/rewards" element={<ProtectedRoute><RewardsPage /></ProtectedRoute>} />
              <Route path="/wallet" element={<ProtectedRoute><WalletPage /></ProtectedRoute>} />
              <Route path="/profile" element={<ProtectedRoute><ProfilePage /></ProtectedRoute>} />
              <Route path="/leaderboard" element={<LeaderboardPage />} />
              <Route path="/login" element={<LoginPage />} />
              <Route path="/register" element={<RegisterPage />} />
            </Routes>
          </main>
          {/* Footer */}
          <footer style={styles.footer}>
            <p>© 2026 Common-Cents. All rights reserved.</p>
          </footer>
        </NavWrapper>
      </div>
    </BrowserRouter>
    </AuthProvider>
  );
}
const styles = {
  app: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background: '#ffffff',
    color: '#ffffff',
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 48px',
    background: '#ffffff',
    borderBottom: '1px solid rgba(10, 22, 40, 0.1)',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
  },
  navBrand: {
    textDecoration: 'none',
  },
  brandText: {
    fontSize: '20px',
    fontWeight: '400',
    fontFamily: "'Inter', system-ui, sans-serif",
    color: '#0a0a1a',
    letterSpacing: '1px',
    textTransform: 'none',
  },
  navLinks: {
    display: 'flex',
    gap: '32px',
  },
  navAuth: {
    display: 'flex',
    alignItems: 'center',
  },
  navLink: {
    color: '#888888',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: '500',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    transition: 'color 0.2s',
  },
  hamburger: {
    background: 'none',
    border: 'none',
    color: '#0a0a1a',
    cursor: 'pointer',
    padding: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileMenuOverlay: {
    position: 'fixed',
    top: '80px',
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 40,
  },
  mobileMenu: {
    position: 'fixed',
    top: '80px',
    left: 0,
    right: 0,
    background: '#ffffff',
    borderBottom: '1px solid rgba(10, 22, 40, 0.1)',
    padding: '16px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    zIndex: 45,
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
  },
  mobileNavLink: {
    color: '#0a0a1a',
    textDecoration: 'none',
    fontSize: '16px',
    fontWeight: '500',
    padding: '12px 0',
    borderBottom: '1px solid rgba(0,0,0,0.05)',
  },
  mobileAuthButtons: {
    paddingTop: '16px',
    borderTop: '1px solid rgba(0,0,0,0.1)',
  },
  loginButton: {
    color: '#888888',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: '500',
    padding: '8px 16px',
    borderRadius: '6px',
    transition: 'all 0.2s',
  },
  registerButton: {
    background: '#22c55e',
    color: '#000000',
    textDecoration: 'none',
    fontSize: '14px',
    fontWeight: '600',
    padding: '8px 16px',
    borderRadius: '6px',
    transition: 'all 0.2s',
  },
  logoutButton: {
    background: 'transparent',
    color: '#888888',
    border: '1px solid #333',
    fontSize: '14px',
    fontWeight: '500',
    padding: '8px 16px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  main: {
    flex: 1,
    paddingTop: '80px',
  },
  footer: {
    padding: '40px 48px',
    background: '#0a0a1a',
    textAlign: 'center',
    color: 'rgba(255,255,255,0.6)',
    fontSize: '14px',
    letterSpacing: '1px',
  },
};
export default App;
